DEFAULT_ENCODING = "utf-8-sig"
DEFAULT_DELIMITER = ";"
DELIMITER_CANDIDATES = (";", ",", "\t", "|")
NULL_VALUES = ("[NULL]", "NULL")
MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024
DATE_DETECTION_SAMPLE_SIZE = 20
DATE_DETECTION_MIN_PARSE_RATE = 0.8
DEFAULT_OUTPUT_DATE_FORMAT = "%Y-%m-%d"
